version: '3'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
